### ISSUE TITLE
dependent libs compilation and linking

### ISSUE THREAD

**Issue by wangii** [tomaka/android-rs-glue#104]
Hi,
Is there a way to pass cargo_apk_xxx env variables to dependencies libs? Say I have a Project MyAndroidApp depends on another lib which needs to link to couple of shared libs (no source code, only .so). my understanding is that:

- write a build.js to manually copy shared libs (.so files) to out_dir.
- compile the rs glue codes with rustup target, and then link against .so files with Android NDK toolchain's linker .

My question is, how to reuse the cc, ld settings already figured out by cargo-apk?  

`cargo-apk` and `android-rs-glue` are great! they finally make Android dev fun! thanks!

**Comment by tomaka** [comment]
You should't need any of the environment variables.
If you have a build script that tells Cargo to link to a specific .so file, then everything is handled automatically.

**Comment by wangii** [comment]
Got it, experimenting.. thanks!
