### ISSUE TITLE
How to set the  android api version?

### ISSUE THREAD

**Issue by zoumi** [tomaka/android-rs-glue#113]
Cargo-Apk: Compiling android_native_app_glue.c
    Cargo-Apk: Compiling injected-glue
    Cargo-Apk: Compiling injected-glue
    Cargo-Apk: Compiling glue_obj
    Cargo-Apk: Compiling crate
    Compiling android_glue_icon_example v0.1.0 (file:///home/zoumi/myprojects/android_example)
    Cargo-Apk: Invoking ant
    Error executing ["ant", "debug"]
    Status code 1
    Stdout
    --------------------
    Buildfile: /home/zoumi/myprojects/android_example/target/android-artifacts/build/build.xml

    -set-mode-check:

    -set-debug-files:

    -check-env:
    [checkenv] Android SDK Tools Revision 24.4.1
    [checkenv] Installed at /home/zoumi/programs/android-sdk-linux

    -setup:
    [echo] Project Name: android_glue_icon_example
    [gettype] Project Type: Application

    -set-debug-mode:

    -debug-obfuscation-check:

    -pre-build:

    -build-setup:
    [getbuildtools] Using latest Build Tools: 24.0.3
    [echo] Resolving Build Target for android_glue_icon_example...
    Stderr
    --------------------

    BUILD FAILED
    /home/zoumi/programs/android-sdk-linux/tools/ant/build.xml:538: Unable to resolve project target 'android-18'

    Total time: 5 seconds

    BUILD FAILED
    /home/zoumi/programs/android-sdk-linux/tools/ant/build.xml:538: Unable to resolve project target 'android-18'

I find out the "SDK Platform Android 4.3.1, API 18" is not installed.But 'SDK Platform Android 4.2.2, API 17' is installed. So,how can I compile with API 17 instead?

**Comment by tomaka** [comment]
You can add a section to your Cargo.toml to indicate this:

```rust
[package.metadata.android]
android_version = 18
```

However Rust only supports Android 18+, so you shouldn't use 17.

**Comment by zoumi** [comment]
@tomaka Thank you!
