### ISSUE TITLE
Add more arguments and use clap to parse the arguments

### ISSUE THREAD

**Issue by tomaka** [tomaka/android-rs-glue#115]
Difficulty level: easy if you're familiar with CLI libraries/medium otherwise.

Lots of issues right now with this crate are the fact that it has a clumsy CLI. Instead of parsing arguments manually, we should probably use an existing library. I like clap but am not against using another one (as long as it is mature enough).

- [ ] The CLI interface of cargo-apk should mimic the one of regular cargo, notably `--help` and the list of subcommands.
- [ ] The `cargo apk build` subcommand should mimic `cargo build`.
- [ ] The `cargo apk install` subcommand should mimic `cargo build`.
- [ ] Add `cargo apk run` that mimics `cargo run` and starts the application on the device (see [this link](http://stackoverflow.com/a/4567928/392546)).
- [ ] The subcommands should return an error if we try to build a library.
- [ ] Add an optional `-s` flag to `install` and `run` that is passed to `adb`, so that the user can choose which device to install to if there are multiple ones.

The internals of this crate work by calling `cargo rustc`. In order to mimic cargo, maybe the best thing to do is simply pass all arguments to cargo, except for `--target` (which is handled internally by this crate).

**Comment by torkleyy** [comment]
I can do that, won't be able to start until next week, though.

**Comment by tomaka** [comment]
Oh, in fact I started doing that just a few days ago: https://github.com/tomaka/android-rs-glue/pull/133
I forgot to link it here.

**Comment by tomaka** [comment]
#133 is now merged.
