### ISSUE TITLE
error running `cargo apk`

### ISSUE THREAD

**Issue by freakypie** [tomaka/android-rs-glue#118]
I followed the tutorial in the README, but when i run `cargo apk` (note, no additional arguments) 
I get:
```
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
Error executing ["cargo", "rustc", "--target", "arm-linux-androideabi", "--", "-C", "linker=~/android-artifacts/linker_exe", "--extern", "cargo_apk_injected_glue=~/target/android-artifacts/arm-linux-androideabi/libcargo_apk_injected_glue.rlib"]
Status code 101
```

my toml
```toml
[package]
name = "rustdl"
version = "0.1.0"
[[bin]]
name = "rustd"
path = "src/main.rs"
[package.metadata.android]
label = "Basic android-rs-glue example"
[dependencies.android_glue]
version = "^0.2"
```

my hello world
```rust
extern crate android_glue;
fn main() { println!("hello world"); }
```

More information
```
NDK_HOME=android-ndk-r13b
```

Can i haz help plz?

**Comment by tomaka** [comment]
I think the problem is that rustc doesn't know whether you want to compile your binary or your library. Cargo-apk doesn't support that yet.

**Comment by freakypie** [comment]
I was trying to make an APK, so a binary, I presume. I'm a rust noob, is there something I forgot to do?

**Comment by tomaka** [comment]
I suppose that you have both a main.rs and a lib.rs. Unfortunately cargo-apk doesn't tell cargo and rustc which one to compile.

Unfortunately there's nothing you can do for this except fix cargo-apk (which is not going to be easy if you're a rust noob :-/)

**Comment by freakypie** [comment]
You said exactly what i needed. There was a lib.rs (a test suite) and after removing that it moved on. Still an error, but i think i can fix it (just missing android 18).

For future reference, is there a way to tell it to ignore the lib.rs?
