### ISSUE TITLE
Manual setup doesn't work on Mac

### ISSUE THREAD

**Issue by wbigger** [tomaka/android-rs-glue#149]
Following the instruction on the [manual section](https://github.com/tomaka/android-rs-glue#manual-usage) of the README, on my mac i get:
```
$ cargo apk install
Could not execute `ant`. Did you install it?
```

Ant is missing indeed. I think it should be downloaded by [Apache](http://ant.apache.org/bindownload.cgi) and add to PATH.

**Comment by tomaka** [comment]
My bad. PR #144 switched from ant to gradle. I updated the README but didn't publish a new version of `cargo-apk`.

**Comment by tomaka** [comment]
Circleci looks down. If you're in a hurry, `cargo install --git https://github.com/tomaka/android-rs-glue/cargo-apk` should work as a replacement.

**Comment by wbigger** [comment]
Thanks!!
