### ISSUE TITLE
Shouldn't `[package.metadata.android]` entries be documented in the README?

### ISSUE THREAD

**Issue by yoanlcq** [tomaka/android-rs-glue#154]
Unless I'm mistaken, the only way to learn about these is by looking at `cargo-apk`'s source code, since the examples merely scratch the surface.

It is my understanding that the `TomlAndroid` struct happens to match the names of supported entries.
```rust
struct TomlAndroid {
    package_name: Option<String>,
    label: Option<String>,
    icon: Option<String>,
    assets: Option<String>,
    res: Option<String>,
    android_version: Option<u32>,
    fullscreen: Option<bool>,
    application_attributes: Option<BTreeMap<String, String>>,
    activity_attributes: Option<BTreeMap<String, String>>,
    build_targets: Option<Vec<String>>,
    opengles_version_major: Option<u8>,
    opengles_version_minor: Option<u8>,
}
```

When I first looked at `android-rs-glue`, I had no idea it supported all of this and was a bit worried (only now do I see the bigger picture). I feel that documenting (or at least mentioning) these in the README (or somewhere else?) would increase the confidence of new users (and prevent NIH people like me from even _considering_ implementing their own solution).

I'm not sure it's worth a pull request, but I'd happily take the time to do it properly if you agree.

**Comment by tomaka** [comment]
> I'm not sure it's worth a pull request, but I'd happily take the time to do it properly if you agree.

That would be nice. I just fear that the README may be a bit overloaded. Maybe it needs to be split into multiple files, I'm not sure.

**Comment by yoanlcq** [comment]
IMO the README happens to be quite lightweight, so I wouldn't worry about adding an extra section at the end. I also think it could benefit from a brief table of contents where appropriate, but I dunno.  

Anyway I guess I'll get started - we'll be able to discuss stuff in reviews.
