### ISSUE TITLE
cargo-apk should be in its own repository

### ISSUE THREAD

**Issue by Redrield** [tomaka/android-rs-glue#159]
This is mainly stylistic, but it does serve a purpose. I'm in the process of making an AUR package for cargo-apk (Because cargo really shouldn't be used as a software manager in the sense that a lot of people are using it as), and versions are uniquely identified by the commit the repo is cloned at. At the moment, cargo-apk commits can't be distinguished from commits to the rest of the library, so there may be people who update the package for no reason.

**Comment by tomaka** [comment]
Cargo-apk is heavily tied to the rest of the repo. Anything in `glue` needs direct support from `cargo-apk` in order to work. Since `glue` aims to provide only the minimum possible low-level features required for Android support, updates that touch the glue alone are rare and will remain rare.
