### ISSUE TITLE
Update Rust in the docker image

### ISSUE THREAD

**Issue by ozkriff** [tomaka/android-rs-glue#166]
See https://github.com/redox-os/rusttype/issues/71#issuecomment-349968771

**Comment by tomaka** [comment]
Same fix as #165

**Comment by ozkriff** [comment]
But how can I upgrade your image at hub.docker.com?

As far as I know (and I'm a total newbie with docker) I can either build my own image on top of yours and upload it to hub.docker.com or call `rustup update` inside the container every time.

**Comment by tomaka** [comment]
No, what I mean is that if I merge a pull request then circle-ci will automatically update the docker image.

**Comment by ozkriff** [comment]
Oh, got it. Give me a second.

**Comment by ozkriff** [comment]
Hmmm, https://hub.docker.com/r/tomaka/cargo-apk doesn't seem to be updated, only https://hub.docker.com/r/tomaka/rust-android is. [Builds are still failing for me](https://circleci.com/gh/ozkriff/zemeroth/268).
