### ISSUE TITLE
Turn apk-builder into a Cargo subcommand

### ISSUE THREAD

**Issue by tomaka** [tomaka/android-rs-glue#18]
I have recently discovered that it was possible to create your own Cargo subcommands.

Instead of using this trick with the linker, a cleaner solution could be for the user to call `cargo android build` or `cargo android-build`.

**Comment by ozkriff** [comment]
Can you give links to docs or examples?

**Comment by tomaka** [comment]
I tried writing something similar for emscripten: https://github.com/tomaka/cargo-emscripten

The content of `src/bin/cargo-emscripten.rs` is more or less the same as `cargo-build.rs` in the official Cargo, except that I pass a `EmscriptenEngine` that is defined in `src/lib.rs`.

It may be a bit difficult to write though. I contributed a bit on Cargo, so I know its internals.

**Comment by tomaka** [comment]
@glennw Would that be OK by the way?
That would require Servo to build differently for android.

**Comment by tomaka** [comment]
This is probably outdated by https://public.etherpad-mozilla.org/p/rustup-new-experience

**Comment by tomaka** [comment]
Done in #75
