### ISSUE TITLE
By-pass the NDK standalone toolchain in apk-builder

### ISSUE THREAD

**Issue by tomaka** [tomaka/android-rs-glue#4]

**Comment by kmcguire3413** [comment]
I wonder if this could be solved partly by a cargo sub-command? If so then it could be simply passed as an argument on the command line, or maybe picked up from the configuration file optionally. I would really like to see this implemented. I may try to see what I can come up with, including looking at the cargo sub-command.

**Comment by tomaka** [comment]
Done in #75
