### ISSUE TITLE
Native shared libraries are not packaged

### ISSUE THREAD

**Issue by mbrubeck** [tomaka/android-rs-glue#41]
Servo's APK should include the libmozjs.so library from the mozjs-sys package, but this library is no longer included in the APK since our latest Rust/Cargo upgrade.  This is because this library is no longer saved to the `native` directory that apk-builder searches in [find_native_libs](https://github.com/tomaka/android-rs-glue/blob/868fb17522f8e4017fe03bfce28e7002307bf714/apk-builder/src/main.rs#L166).  I think this is related to rust-lang/cargo#1195 or other recent changes to Cargo.

I'm trying out a patch here to search the `-L` paths for `*.so` files instead, but this results in false positives, since these paths contain many shared libraries that *don't* need to be packaged (for example, packages that build both static and dynamic libraries, but we only use the static version):  https://github.com/mbrubeck/android-rs-glue/tree/library-path

Alternately, we could change either Cargo or our custom build scripts to put libmozjs.so back in `native` or some other special location that apk-builder can find.

**Comment by larsbergstrom** [comment]
CC @acrichto @brson

**Comment by tomaka** [comment]
The `-lmozjs` parameter is passed to the apk-builder, right? So it should be possible to restrict the list of .so files to the libraries that were passed with `-l`.

**Comment by mbrubeck** [comment]
> The -lmozjs parameter is passed to the apk-builder, right? So it should be possible to restrict the list of .so files to the libraries that were passed with -l.

This looks like it might work, actually.  The static libraries we use are already linked into libmain.so by this point, so they aren't passed as -l parameters to apk-builder.
