### ISSUE TITLE
cargo warning: "warning: unused manifest key: package.metadata.android.@@@"

### ISSUE THREAD

**Issue by ozkriff** [tomaka/android-rs-glue#95]

**Comment by tomaka** [comment]
@acrichton suggested in #75 that we could add a `metadata` section in Cargo whose entries would not trigger this warning. I went ahead and decided to use it.

**Comment by alexcrichton** [comment]
Oops! Forgot to implemented this.. I've posted it over at https://github.com/rust-lang/cargo/pull/2668

**Comment by tomaka** [comment]
This is now fixed.
