### ISSUE TITLE
Trouble when running a simple application in an AVD

### ISSUE THREAD

**Issue by astonbitecode** [tomaka/android-rs-glue#99]
Having installed Rust via rustup and done the steps rdescribed in the README, I have created a simple cargo project with the main being:

```
extern crate android_glue;

fn main() {
    android_glue::write_log("Hello");
    loop {}
}
```

and the Cargo.toml:
```
[package]
name = "hello"
version = "0.1.0"
authors = ["aston"]

[dependencies]
android_glue = "0.2.0"

[[bin]]
name = "hello"
path = "src/hello.rs"

[package.metadata.android]
label = "hello"
```

The compilation with `cargo apk` completes with no problems and moreover, installing it in the Emulator also succeeds.
However, when I try to run it, I get the error that the application has stopped and the log shows:

```
W/dalvikvm( 2296): threadid=1: thread exiting with uncaught exception (group=0xb374e678) E/AndroidRuntime( 2296): FATAL EXCEPTION: main
E/AndroidRuntime( 2296): java.lang.RuntimeException: Unable to start activity ComponentInfo{rust.hello/rust.hello.MainActivity}: java.lang.IllegalArgumentExcept
ion: Unable to find native library: main
E/AndroidRuntime( 2296):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
E/AndroidRuntime( 2296):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
E/AndroidRuntime( 2296):        at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 2296):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 2296):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2296):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2296):        at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 2296):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2296):        at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 2296):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 2296):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2296):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2296): Caused by: java.lang.IllegalArgumentException: Unable to find native library: main
E/AndroidRuntime( 2296):        at android.app.NativeActivity.onCreate(NativeActivity.java:172)
E/AndroidRuntime( 2296):        at android.app.Activity.performCreate(Activity.java:5133)
E/AndroidRuntime( 2296):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 2296):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
E/AndroidRuntime( 2296):        ... 11 more
W/ActivityManager( 1201):   Force finishing activity rust.hello/.MainActivity
I/WindowManager( 1201): Screenshot max retries 4 of Token{b3d3bfd0 ActivityRecord{b3b4ec18 u0 rust.hello/.MainActivity}} appWin=Window{b3bafde0 u0 Starting rust
.hello} drawState=1
W/WindowManager( 1201): Screenshot failure taking screenshot for (480x800) to layer 21015
W/ActivityManager( 1201): Activity pause timeout for ActivityRecord{b3b4ec18 u0 rust.hello/.MainActivity}

```
The AVD that I am using is for _Android 4.3.1 (API level 18)_.

After seeing around in the generated files in `hello/target/android-artifacts/`, I noticed that the generated class in `android-artifacts/build/src/rust/hello/MainActivity.java` is quite empty:

```
package rust.hello;

public class MainActivity extends android.app.NativeActivity {
    static {
        
    }
}
```

Could the problem be that there is no definition like `System.loadLibrary("hello");` or something like that?

**Comment by tomaka** [comment]
It's normal that the class is empty. `android.app.NativeActivity` automatically loads `libmain.so`.

Could you check in `target/android-artifacts/build/libs/armeabi` if there's a `libmain.so`?

**Comment by astonbitecode** [comment]
`libmain.so` exists in `target/android-artifacts/build/libs/armeabi`.

In case is of any help,

`ldd target/android-artifacts/build/libs/armeabi/libmain.so` returns:
> not a dynamic executable

and `file target/android-artifacts/build/libs/armeabi/libmain.so` returns:
> target/android-artifacts/build/libs/armeabi/libmain.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, not stripped

**Comment by tomaka** [comment]
Try `/path/to/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-objdump -T libmain.so | grep ANative`.

And see if it outpuits `ANativeActivity_onCreate`.

**Comment by tomaka** [comment]
Or maybe the other hypothesis is that the .so is in the wrong directory (ie. shouldn't be `armeabi` but for example `arm64` or something).
But I'm not familiar enough with Android to know exactly how it works.

**Comment by astonbitecode** [comment]
The `$NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-objdump -T libmain.so | grep ANative`  
returned:

> $NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-objdump: 'libmain.so': No such file

However, your latest comment reminded me that I was running the emulator using the _Intel/Atom_ CPU/ABI selection (this is recommended because it is supposed to be 10x faster in emulation).

Changing the ABI to to __ARM (armeabi-v7a)__ got the Hello working!
I see in the logs:
`D/RustAndroidGlueStdouterr(  933): Hello`

I too am not an expert for Android, so maybe the issue would be an obvious thing for one... 

Thank you very much for the help!

**Comment by tomaka** [comment]
If you wanted to use the Intel ABI, you'd need to compile your project for x86 in addition to ARM.
This will eventually be possible with an option in the Cargo.toml, but for now only ARM is supported.
